---
maxWeight: 0.01
speed: 0
maxSpeed: 0
massOfFood: 0
matureAge: 1
maxAge: 10
maxEnergy: 0
maxNumberPerCell: 1000
imagePath: src/main/resources/img/icon/caterpillar.png
weight: 0.01
isAlive: true
energy: 0
isBred: false
